### ISSUE TITLE
Improve speech recognition

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/dragonfly_speech_recognition#11]
Take a look at this maybe:

https://github.com/wolfmanstout/dragonfly-commands/blob/master/_repeat.py

**Comment by reinzor** [comment]
http://dragonfly.readthedocs.io/en/latest/elements.html These are the elements we can use in the recognition

**Comment by Rayman** [comment]
Interesting

**Comment by reinzor** [comment]
Closed by https://github.com/tue-robotics/dragonfly_speech_recognition/commit/9a80cc8d1a284b924602b66dc030f0b18fcefcde
