### ISSUE TITLE
Create possibility to enter the to be heared sentence.

### ISSUE THREAD

**Issue by egeerts** [tue-robotics/dragonfly_speech_recognition#6]
Create possibility to enter the to be heared sentence. E.g. by typing in new terminal:
hear go to the livingroom

**Comment by Rayman** [comment]
Implemented in the [continue_gui](https://github.com/tue-robotics/hmi/blob/2812799dbbec1fe9f10c7dbff35be4efac8a0a78/hmi_server/scripts/mocks/continue_gui.py)
