### ISSUE TITLE
server.py holds state

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/dragonfly_speech_recognition#8]
When `def recognize(spec, choices_values, timeout)` is called immediately multiple times, it does not always return the spec of options from that call. It holds state.

Can be tested:
    ears.recognize('banana')
    ears.recognize('apple')
    ears.recognize('pear')

With sleeps in between this works fine but without it, it mixes the specs and choices.

**Comment by LoyVanBeek** [comment]
I think https://github.com/tue-robotics/dragonfly_speech_recognition/blob/master/src/dragonfly_speech_recognition/server.py#L50 may be the culprit.

**Comment by reinzor** [comment]
The thing works really strange. I got it to work with pump waiting messages. Then, I need that global. It is not that easy as just removing this global. I think we have to look to the total code again and see how we can solve this thread thing in a more neat way.

-Rein

**Comment by LoyVanBeek** [comment]
There's only 1 backend to that server and 1 microphone, so blocking and locking might be OK in this scenario
